apiVersion: v1
kind: List
items:
# ConfigMap containing the HTML page
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: html-demo-config
    namespace: jenkins-pipeline-project
  data:
    index.html: |
      <!DOCTYPE html>
      <html>
      <head>
        <title>HTML Demo App</title>
      </head>
      <body>
        <h1>Hello from Jenkins + OpenShift CI/CD!</h1>
        <p>This app is deployed in <strong>jenkins-pipeline-project</strong> namespace.</p>
      </body>
      </html>

# DeploymentConfig using Nginx to serve HTML from ConfigMap
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    name: html-demo
    namespace: jenkins-pipeline-project
  spec:
    replicas: 1
    selector:
      app: html-demo
    template:
      metadata:
        labels:
          app: html-demo
      spec:
        containers:
        - name: html-demo
          image: nginx:latest
          ports:
          - containerPort: 80
          volumeMounts:
          - name: html-volume
            mountPath: /usr/share/nginx/html
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - html-demo
        from:
          kind: ImageStreamTag
          name: "nginx:latest"

    volumes:
    - name: html-volume
      configMap:
        name: html-demo-config
        items:
        - key: index.html
          path: index.html

# Service to expose the deployment
- apiVersion: v1
  kind: Service
  metadata:
    name: html-demo
    namespace: jenkins-pipeline-project
  spec:
    selector:
      app: html-demo
    ports:
    - port: 80
      targetPort: 80

# Route to access the app externally
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: html-demo
    namespace: jenkins-pipeline-project
  spec:
    to:
      kind: Service
      name: html-demo

