apiVersion: v1
kind: ConfigMap
metadata:
  name: html-demo-config
  namespace: jenkins-pipeline-project
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>HTML Demo App</title>
    </head>
    <body>
      <h1>🚀 Welcome to the HTML Demo App!</h1>
      <p>Deployed automatically via Jenkins CI/CD.</p>
    </body>
    </html>

---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: nginx
  namespace: jenkins-pipeline-project
spec:
  tags:
  - name: latest
    from:
      kind: DockerImage
      name: nginx:alpine

---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: html-demo
  namespace: jenkins-pipeline-project
spec:
  replicas: 1
  selector:
    app: html-demo
  template:
    metadata:
      labels:
        app: html-demo
    spec:
      containers:
      - name: html-demo
        image: nginx:alpine
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
          readOnly: true
        - name: nginx-cache
          mountPath: /var/cache/nginx
      volumes:
      - name: html-volume
        configMap:
          name: html-demo-config
          items:
          - key: index.html
            path: index.html
      - name: nginx-cache
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: html-demo
  namespace: jenkins-pipeline-project
spec:
  selector:
    app: html-demo
  ports:
  - port: 8080
    targetPort: 8080

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: html-demo
  namespace: jenkins-pipeline-project
spec:
  to:
    kind: Service
    name: html-demo

